### ISSUE TITLE
References points for the Environments

### ISSUE THREAD

**Issue by oladayosolomon** [LucasAlegre/morl-baselines#15]
Hi! please could you provide the reference points for each of the environments on Mo-gym  or as used in the MORL-baselines

**Comment by ffelten** [comment]
Hi, I am not sure to get what you want ?

Do you want a list of reference points used for the Hypervolume metric? Or for scalarization such as Tchebycheff?

**Comment by oladayosolomon** [comment]
Thanks for your response. yes I mean the reference points used for the hypervolume metric

**Comment by ffelten** [comment]
Well, these depends on the algorithms and thus I'm afraid it depends on the paper. For example, the Deep-Sea-Treasure has been used in many papers and with some different ref points.

Maybe if you could explain what you want to do with it I could help. Otherwise the ref points should be in the original papers.

Cheers,
